# This is a basic workflow to help you get started with Actions

name: CI Build

# Controls when the action will run. 
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
    
jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: npm run test

